### ISSUE TITLE
可以提供帮助手册卸载功能吗

### ISSUE THREAD

**Issue by dong8yong8** [linuxdeepin/deepin-manual#1]
可以提供帮助手册卸载功能吗,
用的时间久了,都不用帮助手册了,
使用终端的时候,不小心碰到F1手册就出来
很烦人

**Comment by BLumia** [comment]
抱歉现在才予以答复，我们之前很少关注汇报在 developer-center 之外的 issue。

你的需求，手动终端执行 `sudo apt remove deepin-manual` 应该就可以了，不过我们不建议卸载帮助手册，所以没有提供界面上的卸载选项。

如果仍你有相关的需求建议的话，可以考虑在 developer-center 发起新的讨论，我们这边会及时进行反馈~
